### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by GemmaTuron** [MedChemLab/TidyScreen_revised#2]
Hi @alfredoq 

We can start by creating the necessary files for TidyScreen to be well documented:

- [x] README.md: should contain a short summary of the project and its aims, a basic installation and usage instruction and other sections like funding, citation, licensing...
- [x] License file: an open source license would be most appropriate for an open project, there is a session in the OLS program about licensing, most common ones include MIT License, Apache, GPLv3...
- [x] CITATION.cff: a [citation](https://citation-file-format.github.io/) file is the best practice for acknowledging software authors
- [x] Requirements: a list of requirements should be specified, either in requirements.txt, setup.py or in the now most widely accepted for pypi packages, a .toml file. We can start with a simple list in a requirements.txt file for example

Hope this is helpful!

**Comment by alfredoq** [comment]
Completed, 

thank you for the suggestions!
